name       : nlopt
version    : 2.4.2
release    : 1
source     :
    - http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz : 8099633de9d71cbc06cd435da993eb424bbcdbded8f803cdaa9fb8c6e09c8e89
license    :
    - LGPL-2.1
    - MIT
component  : programming
patterns   :
    - /usr/include
    - /usr/lib64
summary    : Library for nonlinear optimization
description: |
    Library for nonlinear optimization, wrapping many algorithms for global and local, constrained or unconstrained, optimization.
builddeps  :
    - pkgconfig(guile-2.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
