name       : nlopt
version    : 2.5.0
release    : 2
source     :
    - https://github.com/stevengj/nlopt/archive/v2.5.0.tar.gz : c6dd7a5701fff8ad5ebb45a3dc8e757e61d52658de3918e38bab233e7fd3b4ae
license    :
    - LGPL-2.1-or-later
    - MIT
component  : programming
summary    : Library for nonlinear optimization
description: |
    Library for nonlinear optimization, wrapping many algorithms for global and local, constrained or unconstrained, optimization.
builddeps  :
    - pkgconfig(guile-2.0)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
profile    : |
    %ninja_check
check      : |
    %ninja_check
